### PR TITLE
bash script to export all data from one organisation

### PR DESCRIPTION
**Pull request by adipasquale**
https://trello.com/c/NVvX8hOR/1030-dump-complet-des-donn%C3%A9es-par-organisation

new version of #822 , pure bash script without gem dependency and ruby script

`./scripts/full_orga_sql_dump.sh 83 postgresql://localhost/rdv-sol-prod-dump` 

- outputs one CSV file per table
- outputs one global `full_dump_organisation_XX.sql` file that contains both the schema and data.

in order to do it, the script creates a temporary postgres db on the local machine, but it's dropped before the end of the script

@guillett this is not my most beautiful looking code , sorry. I'm far from being a bash expert 😨 so it's a lot of hacks.

there are a few tricky workarounds to deal with weird cases in the prod db where there's some incoherent data, and also some twists so that foreign keys constraints are respected when the csv files are imported back into a temporary db.

TODO : 
- [ ] export the versions table
- [ ] double check that it's exhaustive and doesn't leak data

### CODE REVIEW

**Comment by guillett** [comment]
:+1: À la place des `exit 1` tu peux mettre tout en haut un `set -e` cf https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html.

**Review by yaf — APPROVED** [review]

**Comment by guillett** [comment]
LGTM :pray:

I added headers to the dumped files (cf commits).

**Comment by guillett** [comment]
I managed to run the script on a local install and local database but I did not manage to run it successfully with the demo db. Could you give it a try before merging that PR? And let me know how you did it :sweat_smile: .

**Comment by adipasquale** [comment]
thanks @guillett , good call for adding headers! 

>  I did not manage to run it successfully with the demo db

I don't understand which demo db you're speaking of?

**Comment by adipasquale** [comment]
should we merge and see how to improve later for the password prompt thing @guillett ?

**Comment by guillett** [comment]
+1

**Comment by guillett** [comment]
:shipit:

**Pull request merged**
