### PR TITLE
Fix agents devise FR translations

### LINKED ISSUE #1140: Pas de traduction dans la demande de changement de mot de passe
Des textes apparaissent en anglais dans les pages de perte de mot de passe / renouvellement de mot de passe.

Capture d’écran de 2021-01-21 12-46-40

### PR DESCRIPTION
**Pull request by Vin0uz**
👋  First contribution here 

Just added devise generated `shared` views, and added 🇫🇷  translations. 
I left all the generated links, some could be cleaned away if not required (model is not lockable for example). I added github in the oauth provider translation list, even though it's not for agents, but this bit could be removed too. 

The spec is super-basic, just testing the translation, not testing the reset password functionnality itself. I would push it in another diff but could be piled on this one I guess 🤔

Closes #1140

Preview: 
image

### CODE REVIEW

**Comment by adipasquale** [comment]
Hi @Vin0uz and thank you very much for this PR 🙇 We'll have a look at it on monday, but it looks fine and we had identified this bug so we're extremely glad you've tackled it !

Would you be willing to share the context in which you're giving rdv-solidarités a spin? All reusages; even commercial, are completely okay and encouraged, since we have a permissive licence. we're just curious as you're one of the first external people to participate to the project !

**Comment by Vin0uz** [comment]
> Hi @Vin0uz and thank you very much for this PR 🙇 We'll have a look at it on monday, but it looks fine and we had identified this bug so we're extremely glad you've tackled it !
> 
> Would you be willing to share the context in which you're giving rdv-solidarités a spin? All reusages; even commercial, are completely okay and encouraged, since we have a permissive licence. we're just curious as you're one of the first external people to participate to the project !

Hi @adipasquale :) 
I just recently wanted to get (more) involved in opensource projects. I gave a look around betagouv projects and found rdv-solidarités, so basically : no reason just pure luck 😄  

I noticed most of comments/issues/commits are in french, is it ok that I do this in english ? (or try to do so at least :trollface:)

**Comment by adipasquale** [comment]
well this justifies even more thanks for helping us out then 🙇 

English or french is perfectly fine for both commits and PR discussions, it's your choice  👌

**Comment by yaf** [comment]
Moi je continue en français parce que je suis plus à l'aise avec :) (déjà que je fais pas mal de faute dans cette langue... :confused: )

**Comment by adipasquale** [comment]
j'ai essayé de corriger la config de CircleCI pour que les builds se déclenchent aussi sur des PR de projets forked mais ça n'a pas l'air d'être rétroactif

**Comment by Vin0uz** [comment]
I'll give it a look tonight, thansk for info and link to the hack 🙌

**Comment by adipasquale** [comment]
@Vin0uz if you want us to finish this PR, let us know, we'd be happy to :)

**Comment by Vin0uz** [comment]
> @Vin0uz if you want us to finish this PR, let us know, we'd be happy to :)

Oh my ! I just forgot to do it, sorry guys ! That's my tonight's mission :)

**Comment by Vin0uz** [comment]
> again, many thanks for your PR which is tackling an issue that we had identified 🙇
> 
> However I think we have to improve one thing before merging it:
> 
> If I click on the "resend confirmation instructions" link I land on a mistraducted page :
> Screenshot 2021-01-25 at 11 33 46
> 
> We could fix this by adding the translations but this would be the 'wrong' fix. What we actually want to do is hide this link altogether.
> 
> Indeed, we have added a small hack in our codebase, so that we have a single interface to ask for a reset password link OR a reconfirm link. We did this because agents were confused in which case they belonged, so we thought it'd be easier to simply have one case: reset password, and it deals with sending the right email.
> 
> The hack is done in https://github.com/betagouv/rdv-solidarites.fr/blob/master/app/controllers/agents/passwords_controller.rb
> 
> I'd be more than happy to update your PR myself @Vin0uz but I thought you may want to do it yourself. Let me know what suits you best 👍

I could not reproduce locally (I didn't know how to "receive" the mail 🙈), but my guess is that this comes from the `shared/links` bit, and one of the link (the confirmation one) leads to `/confirmations/new`. As you said, this page doesn't exist in the codebase, so it's defaulted by devise's one. ([this one](https://github.com/heartcombo/devise/blob/45b831c4ea5a35914037bd27fe88b76d7b3683a4/lib/generators/templates/simple_form_for/confirmations/new.html.erb))

To avoid people accessing it, I removed the link from the shared view. If this hack is planned for long, maybe the `confirmations/new` route should be disabled ? Might be overkill 🤔

**Comment by adipasquale** [comment]
@Vin0uz thanks for your update!

Unfortunately it broke 4 specs: 

- Notifications::Rdv::RdvCreatedService starts today or tomorrow triggers sending mails to both user and agents
- User resets his password spec through password reset page sees proper translation of links
- Notifications::Rdv::RdvDateUpdatedService starts today or tomorrow triggers sending mails to both user and agents (except the one who initiated the change)
- Notifications::Rdv::RdvCancelledService starts today or tomorrow triggers sending mails to the agents (except the one who initiated the change)

I'm not sure how I can give you an access to CircleCI so you can read the output results easily, I'll try.

If you want to discuss how to setup your local env to be able to receive mails, I'd be more than happy to help. By the way we hold an open desk meeting every thursdays from 2.30 to 3.30pm , everyone is welcome to come and discuss with us, mostly social agents but not only. cf https://www.rdv-solidarites.fr/contact you're welcome to join or we can also have a chat at another time more convenient for you.

It'd be a good idea to disable the confirmations controller altogether, good idea 👍  I'll mark it down in our todolist

**Comment by adipasquale** [comment]
oh and again, I'm completely available to take over this PR and finish fixing the specs if you are getting fed up with it / don't have time anymore, don't hesitate to say so!

**Comment by Vin0uz** [comment]
> oh and again, I'm completely available to take over this PR and finish fixing the specs if you are getting fed up with it / don't have time anymore, don't hesitate to say so!

Hi 👋 @adipasquale I didn't check specs locally, my bad, sorry. I can give it a look myself but I do not want to slow down your process so if this PR is urgent, you can definitely take on. 

Thank you for the invitation on Thursday, I ll try to come say hi :)

**Comment by adipasquale** [comment]
@Vin0uz there is no urgency on this matter, so you have all your time, I was only suggesting if you're tired with this PR and want to move on :)

**Comment by Vin0uz** [comment]
> @Vin0uz there is no urgency on this matter, so you have all your time, I was only suggesting if you're tired with this PR and want to move on :)

🙌  Then, I'd gladly finish it myself

**Comment by Vin0uz** [comment]
👋  Fixed one of the spec (`User resets his password spec through password reset page sees proper translation of links`) but others were running fast locally. 
Can you please give me insight about what might be wrong in this diff causing the three others to fail ? 🤔

**Review by adipasquale — APPROVED** [review]
👍

**Pull request merged**
